name: Deployment for branch
on: [ pull_request ]
jobs:
  deploy:
    name: Deploy a branch page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - run: |
          echo ${{ steps.extract_branch.outputs.branch }}

      - name: Build
        shell: bash
        run: |
          mkdir -p ./public/${{ steps.extract_branch.outputs.branch }}
          pushd ./template
          find . -type f -name '*' -exec sed -i 's@{{ branch-name }}@${{ steps.extract_branch.outputs.branch }}@g' {} +
          popd
          cp -r ./template/ ./public/${{ steps.extract_branch.outputs.branch }}/

      - name: LS
        shell: bash
        run: |
          ls -al .
          ls -al template/
          ls -al public/${{ steps.extract_branch.outputs.branch }}/
          git status

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/
          publish_branch: gh-pages
          keep_files: true