name: Deployment for branch
on: [ pull_request ]
jobs:
  deploy:
    name: Deploy a branch page
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch
      - run: |
          echo ${{ steps.extract_branch.outputs.branch }}

      - name: Build
        shell: bash
        run: |
          mkdir -p ./public/${{ steps.extract_branch.outputs.branch }}
          pushd ./template
          find . -type f -name '*' -exec sed -i 's@{{ branch-name }}@${{ steps.extract_branch.outputs.branch }}@g' {} +
          popd
          cp -r ./template/* ./public/${{ steps.extract_branch.outputs.branch }}/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public/
          publish_branch: gh-pages
          keep_files: true


      - name: Get Github Pages URL
        id: extract_pages_url
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')" >> $GITHUB_OUTPUT

      - name: Add link to deployment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            Build will be available at ${{ steps.extract_pages_url.outputs.url }}/${{ steps.extract_branch.outputs.branch }} :wave:
